name: Django CI

on:
  push:
    branches: [ comsem-demo ]
  pull_request:
    branches: [ comsem-demo ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.6', '3.7', '3.8']
      
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 2017%ComSem
          MYSQL_DATABASE: mysql
        ports: ['8080:3306']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env:
          DBENGINE: django.db.backends.mysql
          DBNAME: mysql
          DBUSER: root
          DBPASSWORD: 2017%ComSem
          DBHOST: 127.0.0.1
          DBPORT: $
    - name: Run Tests
      run: |
        python manage.py test
      env:
          DBENGINE: django.db.backends.mysql
          DBNAME: mysql
          DBUSER: root
          DBPASSWORD: 2017%ComSem
          DBHOST: 127.0.0.1
          DBPORT: $
