name: Django CI

on:
  push:
    branches: [ comsem-demo ]
  pull_request:
    branches: [ comsem-demo ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    container:
      image: mysql:5.7
      ports: [8080, 3306]
      
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: zergling
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python $
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --no-binary=:all: -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env:
          DBENGINE: django.db.backends.mysql
          DBNAME: mysql
          DBUSER: root
          DBPASSWORD: zergling
          DBHOST: 127.0.0.1
          DBPORT: $
    - name: Run Tests
      run: |
        python manage.py test
      env:
          DBENGINE: django.db.backends.mysql
          DBNAME: mysql
          DBUSER: root
          DBPASSWORD: zergling
          DBHOST: 127.0.0.1
          DBPORT: $
